#!/usr/bin/env node
/**
 * contracts/ is the SCHEMA OF RECORD. This script generates every TypeScript
 * binding from it. Output is committed and drift-checked; nothing here is
 * hand-edited, and no wire type is declared outside contracts/generated/.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const contracts = join(here, '..');
const outDir = join(contracts, 'generated', 'ts');
mkdirSync(outDir, { recursive: true });

const BANNER = `/**
 * GENERATED FILE - DO NOT EDIT.
 * Source: contracts/ (the schema of record). Regenerate with \`npm run codegen\`.
 * The codegen-drift gate fails the build if this file differs from its source.
 */
`;

// 1. OpenAPI -> TypeScript, for BOTH documents.
//    There are two, deliberately: `openapi.yaml` describes a regional cell and
//    `control-plane-openapi.yaml` describes the Jazzware-internal surface. FR-1 puts
//    Tenant creation on a surface the product does not link to and AD-4 puts the
//    control plane outside the cells, so keeping them apart in the schema of record
//    is what makes an operator credential structurally unable to address a cell -
//    rather than merely unauthorised by a check somebody could widen. The smoke
//    suite asserts the two documents share no path.
const DOCUMENTS = [
  { file: 'openapi.yaml', api: 'api.ts', doc: 'openapi.ts', constant: 'OPENAPI' },
  { file: 'control-plane-openapi.yaml', api: 'control-plane-api.ts', doc: 'control-plane-openapi.ts', constant: 'CONTROL_PLANE_OPENAPI' },
];

for (const d of DOCUMENTS) {
  const api = execFileSync(
    'npx', ['--no-install', 'openapi-typescript', join(contracts, d.file)],
    { encoding: 'utf8', cwd: join(contracts, '..') },
  );
  writeFileSync(join(outDir, d.api), BANNER + api);
}

// 2. Error envelope -> a union the server and both clients share
const env = JSON.parse(readFileSync(join(contracts, 'errors', 'envelope.json'), 'utf8'));
const codes = env.properties.code.enum;
writeFileSync(join(outDir, 'errors.ts'), BANNER +
  `export const ERROR_CODES = ${JSON.stringify(codes)} as const;\n` +
  `export type ErrorCode = (typeof ERROR_CODES)[number];\n`);

// 3. Locale keys -> a union, so a missing key is a compile error not a blank label
const en = JSON.parse(readFileSync(join(contracts, 'locale', 'en.json'), 'utf8'));
const keys = Object.keys(en).sort();
writeFileSync(join(outDir, 'locale-keys.ts'), BANNER +
  `export const LOCALE_KEYS = ${JSON.stringify(keys, null, 2)} as const;\n` +
  `export type LocaleKey = (typeof LOCALE_KEYS)[number];\n`);

// 4. The OpenAPI document as a module.
//    The runtime image does NOT ship contracts/ - only dist, node_modules and the
//    migration SQL - so the server cannot read openapi.yaml from disk. Compiling it
//    in is the only thing that works in the container, and it earns drift-gate
//    coverage: edit the YAML without regenerating and CI fails.
for (const d of DOCUMENTS) {
  const spec = parseYaml(readFileSync(join(contracts, d.file), 'utf8'));
  writeFileSync(join(outDir, d.doc), BANNER +
    `/* eslint-disable */\n` +
    `export const ${d.constant}_DOCUMENT = ${JSON.stringify(spec, null, 2)} as const;\n` +
    `export const ${d.constant}_VERSION = ${JSON.stringify(spec.info.version)};\n`);
}

// 5. SLA fixture vector shape, so the gate and the fold agree on the file's schema
const vectors = JSON.parse(readFileSync(join(contracts, 'sla-fixtures', 'vectors.json'), 'utf8'));
writeFileSync(join(outDir, 'sla-fixtures.ts'), BANNER +
  `export const SLA_FIXTURE_FOLD_VERSION = ${vectors.foldVersion};\n` +
  `export const SLA_FIXTURE_COUNT = ${vectors.vectors.length};\n`);

console.log(`codegen: wrote 7 TypeScript bindings to contracts/generated/ts (2 OpenAPI documents)`);
console.log(`codegen: Dart bindings are generated by the Flutter toolchain (Stories 4.x); the drift gate covers whatever exists.`);
